/*
 * Project name:
     pressure.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     9/17/2024
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Mikromedia_5_for_STM32_Capacitive
     Oscillator:      168000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "pressure_objects.h"
#include "pressure_resources.h"
#include "Click_Pressure8_types.h"
#include "Click_Pressure8_config.h"
float PressureData, readADC, press;
char demoText[ 50 ], text[20];
int x,y;

void InitTimer2(){
  RCC_APB1ENR.TIM2EN = 1;
  TIM2_CR1.CEN = 0;
  TIM2_PSC = 279;
  TIM2_ARR = 59999;
  NVIC_IntEnable(IVT_INT_TIM2);
  TIM2_DIER.UIE = 1;
  TIM2_CR1.CEN = 1;
}


void systemInit()
{
//    mikrobus_gpioInit( _MIKROBUS1, _MIKROBUS_INT_PIN, _GPIO_INPUT );
//    mikrobus_gpioInit( _MIKROBUS1, _MIKROBUS_RST_PIN, _GPIO_OUTPUT );
//    mikrobus_i2cInit( _MIKROBUS1, &_PRESSURE8_I2C_CFG[0] );
    mikrobus_logInit( _MIKROBUS1, 9600 );
    mikrobus_logWrite("--- System Init ---", _LOG_LINE);
    Delay_ms( 100 );
}

void applicationInit()
{
//    pressure8_i2cDriverInit( (T_PRESSURE8_P)&_MIKROBUS1_GPIO, (T_PRESSURE8_P)&_MIKROBUS1_I2C, 0x18 );
//    pressure8_reset();
//    pressure8_setPSIRange(0, 25);
    InitTimer2();
    ADC1_Init();
    ADC_Set_Input_Channel( _ADC_CHANNEL_4);
    Delay_ms(200);
}

 void bingkai(unsigned dat)
{
    x = 350;y = 110;
    TFT_Set_Pen(CL_BLACK, 1);
    TFT_Set_Brush(1, 0,0, LEFT_TO_RIGHT, CL_BLACK, CL_BLACK);
    TFT_Rectangle(x, y, x+110, y+100);
    TFT_Set_Pen(CL_WHITE, 5);
    TFT_Set_Font(Tahoma26x33_Regular, CL_WHITE, FO_HORIZONTAL);
    FloatToStr(dat, text );
    TFT_Write_Text(text, x, y);
    Delay_ms(10);
}

void applicationTask()
{
      readADC = ADC1_Get_Sample(4);
      press = (float)(readADC*(3.3/4095));

      PressureData = (press/3.3)*25.0;
//      PressureData = pressure8_getPressure(_PRESSURE8_DATA_IN_mBar);
      FloatToStr(PressureData, demoText);
      bingkai(   PressureData  );
//      PressureData[i]= 2*sin(2*3.14*25*i);
//      TFT_Set_Pen(CL_BLACK,1);
//      TFT_V_Line(0, 400, i);
//      TFT_Set_Pen(CL_YELLOW,1);
//      TFT_Line(i-1,260-50*PressureData[i], i , 260-50*PressureData[i]);
      mikrobus_logWrite(" Pressure data : ", _LOG_TEXT);
      mikrobus_logWrite(demoText, _LOG_TEXT);
      mikrobus_logWrite(" mBar", _LOG_LINE);
      Delay_ms( 1000 );
}

void Timer2_interrupt() iv IVT_INT_TIM2 {
  TIM2_SR.UIF = 0;
  //Enter your code here
}

void main() {
     Start_TP();
    systemInit();
    applicationInit();

  while (1) {
//    Check_TP();
        applicationTask();
  }
}